"""add email_attachments table

Revision ID: fcbd97f9fa5d
Revises: 3f1532e63427
Create Date: 2026-02-10 15:00:05.039022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbd97f9fa5d'
down_revision: Union[str, Sequence[str], None] = '3f1532e63427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_id'), 'email_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_email_attachments_thread_id'), 'email_attachments', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_attachments_thread_id'), table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    # ### end Alembic commands ###
